# Generated by Django 3.2.15 on 2022-10-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('corr_ans', models.CharField(max_length=1000)),
                ('inc_ans1', models.CharField(max_length=1000)),
                ('inc_ans2', models.CharField(max_length=1000)),
                ('inc_ans3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('resource1', models.BooleanField(default=False)),
                ('resource2', models.BooleanField(default=False)),
                ('resource3', models.BooleanField(default=False)),
                ('resource4', models.BooleanField(default=False)),
                ('resource5', models.BooleanField(default=False)),
                ('resource6', models.BooleanField(default=False)),
                ('resource7', models.BooleanField(default=False)),
                ('resource8', models.BooleanField(default=False)),
                ('resource9', models.BooleanField(default=False)),
                ('resource10', models.BooleanField(default=False)),
                ('resource11', models.BooleanField(default=False)),
                ('resource12', models.BooleanField(default=False)),
                ('quiz_complete', django_postgres_extensions.models.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True)),
                ('quiz_score', models.IntegerField(default=0)),
                ('curr_quiz_index', models.IntegerField(default=0)),
                ('curr_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incskill_site.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
