# Generated by Django 3.2.15 on 2022-10-24 16:15

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quiz_complete',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True),
        ),
    ]
