# Generated by Django 3.2.15 on 2022-10-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('corr_ans', models.CharField(max_length=1000)),
                ('inc_ans1', models.CharField(max_length=1000)),
                ('inc_ans2', models.CharField(max_length=1000)),
                ('inc_ans3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='curr_quiz_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pot_quiz_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
