# Generated by Django 3.2.15 on 2022-10-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0002_auto_20221014_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_quiz_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pot_quiz_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
