# Generated by Django 3.2.15 on 2022-10-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0002_auto_20221014_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quiz',
            field=models.BooleanField(default=False),
        ),
    ]
