# Generated by Django 3.2.15 on 2022-10-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0002_auto_20221018_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incskill_site.question'),
        ),
    ]
