# Generated by Django 3.2.15 on 2022-10-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0003_auto_20221018_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('corr_ans', models.CharField(max_length=1000)),
                ('inc_ans1', models.CharField(max_length=1000)),
                ('inc_ans2', models.CharField(max_length=1000)),
                ('inc_ans3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='curr_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='incskill_site.question'),
        ),
    ]
