# Generated by Django 3.2.15 on 2022-10-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0004_auto_20221018_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='curr_question',
        ),
    ]
