# Generated by Django 3.2.15 on 2022-10-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0005_remove_profile_curr_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_question',
            field=models.ForeignKey(default='IT', on_delete=django.db.models.deletion.CASCADE, to='incskill_site.question'),
        ),
    ]
