# Generated by Django 3.2.15 on 2022-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incskill_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resource10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='resource9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remainingProgress',
            field=models.FloatField(default=100.0),
        ),
    ]
